apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-devops
  namespace: devops
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: "128Mi"
    defaultRequest: # this section defines default requests
      cpu: 200m
      memory: "64Mi"
    type: Container
