apiVersion: v1
kind: Pod
metadata:
   name: sec-pod
   labels:
     app: wordpress
spec:
   containers:
   - name: con1
     image: nginx:latest
     ports:
     - containerPort: 80
     volumeMounts:
     - name: myvol
       mountPath: /data
   volumes:
   - name: myvol
     secret:
       secretName: mycrt
---

